development:
  adapter: solr
  url: http://localhost:8983/solr/conflicts
  schema: conflicts/schema.json
test:
  adapter: solr
  url: http://localhost:8983/solr/conflicts
  schema: conflicts/schema.json
production:
  adapter: solr
  url: http://localhost:8983/solr/conflicts
  schema: conflicts/schema.json